### ISSUE TITLE
How to specify @Level for ingested log events using --extract

### ISSUE THREAD

**Issue by robbiedhickey** [datalust/seqcli#100]
My current use case is using the `--extract` flag to ingest IIS logs into Seq, and I'm having trouble figuring out how to set the @Level property of each log event (the W3C format does not have a level concept). The documentation examples are all around log formats that have an extractable log level within the log line. Is there way to either set @Level explicitly in the extract template, or to provide a default log level for the entire ingestion?

I've tried adding the assignment in the extract template but it seems wrong since there is no token for seq-cli to parse:

-x "{@t:w3cdt} {ServerIP} {@m:={Method} {RequestPath} {Query}} {Port:nat} {Username} {ClientIP} {UserAgent} {Referer} {StatusCode:nat} {Substatus:nat} {Win32Status:nat} {ResponseBytes:nat} {RequestBytes:nat} {Elapsed:nat}{:n} **{@l:=Debug}**"

Do you know if there is any way to accomplish this? 

I noticed that the `log` sub-command has a `--level` option, maybe `ingest` could support the same flag?

**Comment by nblumhardt** [comment]
Thanks for the suggestion. Yes, having some mechanism for setting fields not in the log line would be great.

The `seqcli ingest` command already supports `-p Name=Value` syntax for additional, non-"special" properties; perhaps we could just extend this like so?

```
seqcli ingest -i foo.txt -x "..." -p @l=Debug
```

The `@` may have special meaning in some shells, though, so I guess this would have to allow escaping: `"@l"="Debug"`, ideally, since we'd need to allow for values with embedded punctuation and whitespace.

One nice outcome from this would be that in your example, instead of extracting a portion of the log line to make a non-templated message `@m`, the command could specify a message template:

```
... -p @mt="IIS {Method} {RequestPath} returned {StatusCode} in {Elapsed} ms"
```

and therefore get nice rendering + event types in Seq..... :-)

**Comment by nblumhardt** [comment]
I started down this path and realised the CLI would then be inconsistent between `ingest` and `log`, since `log` already accepts a level with `-l` and a message template with `-m`.

PR #101 implements this.
