### ISSUE TITLE
Seq 4.x compatibility

### ISSUE THREAD

**Issue by kdiddy82** [datalust/seqcli#76]
While trying to run 'seqcli apikey list' , I get the following failure:  The command failed: The URI template `api/apikeys` does not contain parameter: `ownerId`.

The version of the CLI is 0.1.153 for win64, the version of Seq is 4.2.113

**Comment by nblumhardt** [comment]
Thanks for the report, @kdiddy82.

While `seqcli` is in development, we're only focusing on Seq 5 compatibility - it's uncertain whether complete 4.2 compat will be added after the fact, though, because the limited permissions available to API keys in v4 means that many of the current CLI scenarios aren't able to be supported.

Sorry about the inconvenience. I'll leave this open as a "4.2 compat" discussion in case there are other angles we haven't considered.

**Comment by kdiddy82** [comment]
Hi,

Thanks for getting back so quick.  I didn’t see that it was in development.

However, I’ve gone the route of using the API via Powershell. (not the Seq.Api nuget package)

My script is working locally on my development machine where I do not have any authentication setup.  However when I move to our other Seq instances, I’m getting a 401 Unauthorized.  Do you have any examples of how to authenticate via the API ?

Preferably something that utilizes Powershell.

Thanks for your time,

Kyle

**Comment by nblumhardt** [comment]
Hi Kyle, thanks for the reply. Depending on the authentication method in use, this may be possible via username/password authentication in PowerShell. It might be better to continue the discussion by email? If so, we're support@getseq.net, if you can let us know whether you're using basic, AD, or AAD auth I will take a look. Thanks!

**Comment by nblumhardt** [comment]
Hi again; I think things have moved on since we last discussed this - let me know if you still need any help at all, Kyle. Cheers!
